[project]
name = "pytest-flakiness"
dynamic = ["version"]
description = "Pytest reporter for Flakiness.io"
readme = "README.md"
authors = [
    { name = "Andrey Lushnikov", email = "aslushnikov@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "brotli>=1.2.0",
    "pytest>=9.0.2",
    "requests>=2.32.5",
]

[project.urls]
Homepage = "https://flakiness.io/"
Documentation = "https://flakiness.io/docs"
Repository = "https://github.com/flakiness/pytest-flakiness"
Issues = "https://github.com/flakiness/pytest-flakiness/issues"

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
fallback-version = "0.0.0"

[dependency-groups]
dev = [
    "pre-commit>=4.5.0",
    "pyright>=1.1.407",
    "ruff>=0.14.8",
]

[project.entry-points.pytest11]
flakiness = "pytest_flakiness.plugin"
